### ISSUE TITLE
Document has wrong link

### ISSUE THREAD

**Issue by duskybomb** [OpenBCI/Docs#110]
The Docs Page on your website has a wrong url.
  
http://docs.openbci.com/Headware/01-Ultracortex-Mark-IV
In Hardware Section, under Ultracortex Mark IV, the link to Comfort Units is wrong,
(https://github.com/OpenBCI/Docs/blob/master/assets/MarkIV/Photos/ConfortUnits.JPG).

![screenshot 56](https://user-images.githubusercontent.com/13499577/32263756-3e39c92e-bf01-11e7-8f83-6910c25ff22e.png)

**Comment by RebeccaMurray** [comment]
Fixed the typo in the link. Thanks!
