### ISSUE TITLE
Incorrect Part number for PIC32 in Cyton BOM

### ISSUE THREAD

**Issue by karan259** [OpenBCI/Docs#111]
The part in the Cyton BOM here http://docs.openbci.com/Hardware/02-Cyton says U7 should be PIC32MX250F128B-I/ML, however this points here https://www.digikey.com/products/en?keywords=PIC32MX250F128B-I%2FML to the same chip with a different package. The part number should be PIC32MX250F128B-I/SS which has SSOP28 package

**Comment by biomurph** [comment]
Thanks, I updated the link. Now it goes to the correct BOM and plot files.
