### ISSUE TITLE
Spike unit electrodes possible change with other spike untis by keeping the plastic-mountic system, or not possible ?

### ISSUE THREAD

**Issue by tzvet** [OpenBCI/Docs#115]
Hello !

I am not sure this question is for here but looking around i think this place is the most suitable.

I was looking at some plausible "add-ons" for the spike units and found this dry electrodes:
https://fri-fl-shop.com/product/new-longer-5mm-spike-disposable-reusable-dry-eeg-electrode-tde-210/

I am not sure of one point, whether this electrode shape matches the current plastic-molded design OpenBCI gives with the already mounted spike-units. I disassembled one, and the sizes seem more or less fitting.

Does anyone at OpenBCI has an idea whether this "longer spike units" (5mm!) would be fitting to the plastic parts ?

thanks for any feedback.

**Comment by ThreeForm** [comment]
Yes, they should be compatible. The Ultracortex headset was designed with electrodes compatible with the original FRI ones, so assuming those are interchangeable, this should work.
