### ISSUE TITLE
Connect Ganglion to OpenViBE on Linux?

### ISSUE THREAD

**Issue by brylie** [OpenBCI/Docs#148]
I would like to connect my OpenBCI Ganglion to the OpenViBE Acquisition Server, so that I can get OpenBCI data into OpenViBE. The [instrucitons](http://docs.openbci.com/3rd%20Party%20Software/03-OpenViBE) give some detail about Windows, but not Linux. How do I connect a Ganglion device to Linux as a USB COM port?

**Comment by retiutut** [comment]
https://github.com/OpenBCI/OpenBCI_GUI/issues/463#issuecomment-476856858
