### ISSUE TITLE
Search cannot find Ganglion

### ISSUE THREAD

**Issue by SpinReactor** [OpenBCI/Docs#149]
I am trying to connect the Ganglion with the OpenBCI GUI without luck when I search for BLE devices. I am running a CSR bluetooth 4.0 dongle but the Ganglion doesn't show up anywhere except on my phone. I have updated the firmware and searched the forums but cannot find anything else to troubleshoot. This is new and has never worked before. I have tried connecting with Elecguro and Brainbay without success. 

I'm on a Dell laptop running windows 10

**Comment by retiutut** [comment]
The CSR documents are now under "Deprecated" https://github.com/OpenBCI/Docs/blob/master/Deprecated%20Docs/Setup_CSR_Dongle.md
