### ISSUE TITLE
In the Cyton tutorial, Suggest "AUTOSCAN" under Troubleshooting

### ISSUE THREAD

**Issue by daniellasry** [OpenBCI/Docs#155]
In the docs under Tutorials->Cyton Getting Started Guide, scroll down to "TROUBLESHOOTING".

The list of troubleshooting steps should suggest trying "AUTOSCAN" if no data is streaming from Cyton. The dongle and device could be on different channels and the user wouldn't know.

**Comment by shirleyzhang867** [comment]
I edited the section under troubleshooting to include the "AUTOSCAN" suggestion
