### ISSUE TITLE
Cyton+Wifi Add a note about the D4 led turning off when switching to analog mode

### ISSUE THREAD

**Issue by daniellasry** [OpenBCI/Docs#156]
This was prompted by OpenBCI/OpenBCI_WIFI#86

Cyton + Wifi Shield:
When switching the board mode to analog/aux, the D4 light turns off. This can be done in the OpenBCI GUI, or running this in python:
```
from openbci import wifi as bci
shield = bci.OpenBCIWiFi(ip_address = '192.168.1.141', log=True, high_speed=True)
shield.wifi_write('/2') #analog mode
```

Observe that light D4 turns off. This is normal, and has something to do with some pins being in use by the Wifi shield, forcing the light to turn off.

It would be good to get clarity on how this works and add a note in the Docs about it. Perhaps in the Wifi getting started tutorial, or in the Wifi Hardware page.

**Comment by leanneapichay** [comment]
Consulted AJ about this issues, who said "In order for the LED to turn on the Cyton has to set that pin as an output HIGH. When the cyton switches into digital/analog inputs it changes the pin driving the D4 LED to INPUT, so the is no longer receiving any current to turn on."

Added this to the Wifi Getting Started Tutorial under the Cyton section.
