### ISSUE TITLE
CUSTOM GUI WIDGETS: Add new widget settings to SoftwareSettings.pde for saving/loading

### ISSUE THREAD

**Issue by daniellasry** [OpenBCI/Docs#158]
There should be a note in the [CUSTOM GUI WIDGETS](http://docs.openbci.com/Tutorials/16-Custom_Widgets) tutorial about [adding new widget setting to SoftwareSettings.pde for saving and loading.](https://github.com/OpenBCI/OpenBCI_GUI/issues/328#issuecomment-451666283)

**Comment by retiutut** [comment]
Yes!
