### ISSUE TITLE
OpenBCI_GUI is damaged on Mac

### ISSUE THREAD

**Issue by igweckay** [OpenBCI/Docs#16]
<img width="419" alt="screen shot 2016-05-25 at 1 44 09 pm" src="https://cloud.githubusercontent.com/assets/8213713/15554841/f3c848b2-2293-11e6-80a6-233a2916de2e.png">

**Comment by ThreeForm** [comment]
I'm not on a Mac, but we'll have someone take a look.

**Comment by teonbrooks** [comment]
hey @igweckay, you need to change the permission in your system preferences to allow third-party app to be opened.
System Preference > Security and Privacy > Allow App downloaded from > Anywhere.

If this fixes your problem, feel free to close. 

HTH

**Comment by andrewjaykeller** [comment]
If this issue is still persisting, please open the issue on `OpenBCI_GUI`
