### ISSUE TITLE
OpenBCI with Openvibe

### ISSUE THREAD

**Issue by ra75763** [OpenBCI/Docs#168]
Hi ,

I need to complete P300test. I have Ultracortex mark IV headset and by OPenBCI Gui, I could run cyton board successfully. But when I want to interface with OpenVIbe v 2.2, it didn't connect. Like: It not showing the COM3 port on Openvibe. It means, it can't detect Dongle port. Can you give me some outline ? Operating system is W10

<img width="1675" alt="pr1" src="https://user-images.githubusercontent.com/47288237/52214846-a8793d00-2860-11e9-927c-9db948e618bf.png">
<img width="986" alt="pr2" src="https://user-images.githubusercontent.com/47288237/52214847-a8793d00-2860-11e9-85dc-f5af17f4e714.png">

**Comment by retiutut** [comment]
https://github.com/OpenBCI/Docs/edit/master/3rd%20Party%20Software/03-OpenViBE.md

This Doc currently describes how to connect directly to the Cyton board. Another way is to connect the Board to the GUI, and then stream LSL to openVibe acquisition server.
