### ISSUE TITLE
What does "Items that have been opened will not be accepted." exactly mean ?

### ISSUE THREAD

**Issue by silbo** [OpenBCI/Docs#177]
It is a bit confusing to read the return policy where on the one hand it's mentioned: "Items that have been opened will not be accepted." and on the other: "Please note, all returns are contingent on the resale-able condition of the items."

So in what case can the purchase be returned in 30 days of receipt ?

**Comment by shirleyzhang867** [comment]
If you have received a nonfunctional product, you may return it within 30 days of receipt. If you decide to return the product for other reasons, it must be unopened.

**Comment by silbo** [comment]
Thank you for the fast reply.
