### ISSUE TITLE
Bad link to Forum from Docs page

### ISSUE THREAD

**Issue by mdroberts1243** [OpenBCI/Docs#236]
The link to the FORUM from the Docs pages seems to be bad:
https://openbci.com/index.php/forum/ 

Frustrating 404 everytime I try to use it inadvertently.

**Comment by retiutut** [comment]
This repo is going away. Please remake this issue in Documentation. EZ fix.

**Comment by retiutut** [comment]
https://github.com/OpenBCI/Documentation

**Comment by retiutut** [comment]
I've copied the issue for you.

**Comment by retiutut** [comment]
https://openbci.github.io/Documentation/
