### ISSUE TITLE
Messed Ultracortex MarkIV Large Quads Naming

### ISSUE THREAD

**Issue by VIVelev** [OpenBCI/Docs#237]
The names of the large quads in https://github.com/OpenBCI/Docs/tree/master/assets/MarkIV/STL_Directory/Mark_IV_Frame/Mark_IV_Frame_Quads are messed up.

*M4_Large_Back_Left* **should be** *M4_Large_Front_Right*
*M4_Large_Back_Right* **should be** *M4_Large_Back_Left*
*M4_Large_Front_Left* **should be** *M4_Large_Back_Right*
*M4_Large_Front_Right* **should be** *M4_Large_Front_Left*

**Comment by VIVelev** [comment]
Do you want me to pull request with the fix?

**Comment by retiutut** [comment]
These Docs are no longer active.

**Comment by retiutut** [comment]
https://github.com/OpenBCI/Documentation

**Comment by retiutut** [comment]
Where did you find a link to these files? Do we need to move them to the new Docs also?

**Comment by VIVelev** [comment]
I found them here: https://openbci.github.io/Documentation/docs/04AddOns/01-Headwear/MarkIV#3d-printed-parts-1

> You can also print the frame in quarters or print the full frame. The .stl files are found here.


I needed these files because my 3D printer was too small to print the MarkIV by halves.

**Comment by VIVelev** [comment]
I believe it will be usefull to add them to the new Docs also :)

**Comment by retiutut** [comment]
@VIVelev You're welcome to make the Pull Request with this info in the new Docs repo. Thank you for noticing this.

**Comment by VIVelev** [comment]
Great, I'm going to pr as soon as possible.

Maybe add the files to `Documentation/docs/assets/MarkIV` ?

**Comment by VIVelev** [comment]
@retiutut Wouldn’t it be better to add the files to the [Ultracortex](https://github.com/OpenBCI/Ultracortex) repo under the folder `MarkIV`, since it's a more relevant place for those type of files.

**Comment by retiutut** [comment]
@VIVelev So I guess the Ultracortex Mark IV file names need to be changed there then? 

And then we change the links in the https://github.com/OpenBCI/Documentation  to the https://github.com/OpenBCI/Ultracortex repo.

**Comment by VIVelev** [comment]
Yes, pretty much.

The STL files for the quads need to be added to `/Ultracortex/Mark_IV/MarkIV-FINAL/STL_Directory/` named properly. And then, as you said, we change the links in the https://github.com/OpenBCI/Documentation to the https://github.com/OpenBCI/Ultracortex repo.

**Comment by retiutut** [comment]
@VIVelev Confirmed this naming bug just now. Looks like just for Large size yeah?

**Comment by VIVelev** [comment]
@retiutut Also for the Medium, Small sizes: Left and Right should be swapped respectively.
(Front_Left -> Front_Right, Front_Right -> Front_Left and the same for Back)

**Comment by VIVelev** [comment]
@retiutut I am going to PR the right naming in a minute or so to the Ultracortex repo

**Comment by retiutut** [comment]
@VIVelev All you have to do is "fork" the repo, make changes locally, push changes to your branch, then make a Pull Request. I can help with changing the links in the new Docs.

**Comment by retiutut** [comment]
@VIVelev No rush it's still the weekend lol

**Comment by VIVelev** [comment]
@retiutut Yeah, no worries.

I am high school student and I am in a summer vacation still. 
I have plenty of time. :D
