### ISSUE TITLE
RFLoader Broken Link

### ISSUE THREAD

**Issue by baffo32** [OpenBCI/Docs#73]
Hi,

http://docs.openbci.com/Hardware/06-Cyton_Radios_Programming_Tutorial specifies to download RFLoader.exe from http://docs.openbci.com/assets/RFDLoader for programming the radios on Linux.  However, this file is not available at this address.

- Karl

**Comment by baffo32** [comment]
Looks like the correct URL is https://github.com/OpenBCI/OpenBCI_RFduino/raw/master/RFduino/RFDLoader.exe

**Comment by biomurph** [comment]
Thanks!

**Comment by baffo32** [comment]
Sorry, this fix was not correct.  It looks like some kind of wrapper script is expected that launches the exe using wine, not the exe itself.

**Comment by baffo32** [comment]
I wrote this script which worked for me when saved as `RFDLoader`:
```
#!/bin/bash
mkdir -p ~/.wine/dosdevices
ln -sf "$2" ~/.wine/dosdevices/com9
wine "$0".exe "$1" com9 "$3"
```
I'm guessing the original script, which seems to have disappeared, contained something similar.
