### ISSUE TITLE
I am trying to document compiling the gangleon design into a piece of hardware using macrofab service and documenting it in the wiki

### ISSUE THREAD

**Issue by josheeg** [OpenBCI/Docs#87]
I am trying to document compiling the gangleon design into a piece of hardware using macrofab service and documenting it in the wiki.

https://github.com/OpenBCI/Docs/wiki/Compile-Open-Source-Hardware-OpenBCI-Gangleon-process.-v1-lets-make-something-great-and-better-together.-:D

**Comment by biomurph** [comment]
I created the first wiki page on the ganglion repo. Please post there
